name: runway
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_svg: ^2.1.0
  gap: ^3.0.1
  video_player: ^2.10.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/category/
    - assets/images/icons/
    - assets/images/logo/
    - assets/images/man_category/
    - assets/video/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
flutter_assets:
  assets_path: assets/
  output_path: lib/core/utils/
  filename: assets.dart
  field_prefix: null
